spring:
  datasource:
    url: jdbc:sqlite:./orion.db?busy_timeout=5000&journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
  flyway:
    validate-on-migrate: false

logging:
  level:
    com.axon.orion: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
